BASE_URL = "https://stellarburgers.nomoreparties.site"
USER_REGISTER_URL = "https://stellarburgers.nomoreparties.site/api/auth/register"
USER_LOGIN_URL = "https://stellarburgers.nomoreparties.site/api/auth/login"
USER_URL = "https://stellarburgers.nomoreparties.site/api/auth/user"
INGREDIENTS_URL = "https://stellarburgers.nomoreparties.site/api/ingredients"
ORDERS_URL = "https://stellarburgers.nomoreparties.site/api/orders"
